gb_project/gb_project/urls.py
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello_app/', include('hello_app.urls', namespace="hello_app")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gb_project/hello_app/urls.py
from django.urls import path
from . import views


app_name = 'hello_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('client_orders/<int:client_id>/', views.client_orders, name='client_orders'),
]

gb_project/hello_app/models.py
from django.db import models
from django.utils import timezone


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    registration_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    added_date = models.DateTimeField(default=timezone.now)
    photo = models.ImageField(upload_to='product_photos/', blank=True, null=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Order #{self.id} by {self.client.name}"

gb_project/hello_app/forms.py
from django import forms
from .models import Product


class ProductPhotoForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['photo']

gb_project/hello_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import ProductPhotoForm
from django.utils import timezone
from datetime import timedelta
from .models import Client, Product, Order

import logging

logger = logging.getLogger(__name__)


def index(request):
    logger.info('Пользователь посетил главную страницу')

    html = """
    <html>
    <head><title>Главная страница</title></head>
    <body>
        <h1>Добро пожаловать на мой первый Django-сайт!</h1>
        <p>Здесь вы найдете информацию обо мне и о моем сайте.</p>
    </body>
    </html>
    """
    return HttpResponse(html)


def about(request):
    logger.info('Пользователь посетил страницу "О себе"')

    html = """
    <html>
    <head><title>О себе</title></head>
    <body>
        <h1>Обо мне</h1>
        <p>Здесь вы найдете информацию обо мне.</p>
    </body>
    </html>
    """
    return HttpResponse(html)


def client_orders(request, client_id):
    client = Client.objects.get(pk=client_id)

    # Определение дат для фильтрации заказов
    today = timezone.now()
    week_ago = today - timedelta(days=7)
    month_ago = today - timedelta(days=30)
    year_ago = today - timedelta(days=365)

    # Фильтрация заказов клиента за последнюю неделю, месяц и год
    orders_week = client.order_set.filter(order_date__gte=week_ago)
    orders_month = client.order_set.filter(order_date__gte=month_ago)
    orders_year = client.order_set.filter(order_date__gte=year_ago)

    context = {
        'client': client,
        'orders_week': orders_week,
        'orders_month': orders_month,
        'orders_year': orders_year,
    }

    return render(request, 'client_orders.html', context)


def upload_product_photo(request):
    if request.method == 'POST':
        form = ProductPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('about')
    else:
        form = ProductPhotoForm()
    return render(request, 'upload_product_photo.html', {'form': form})

gb_project/hello_app/templates/hello_app/client_orders.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <title>Заказы клиентов</title>
</head>
<body>
<h1>Заказы за {{ client.name }}</h1>

<h2>Заказы за Неделю:</h2>
<ul>
    {% for order in orders_week %}
    {% for product in order.products.all %}
    {% if not product.id in products_ids %}
    <li>{{ product.name }}</li>
    {% with products_ids|add:product.id as products_ids %}
    {% endwith %}
    {% endif %}
    {% endfor %}
    {% endfor %}
</ul>

<h2>Заказы за Месяц:</h2>
<ul>
    {% for order in orders_month %}
    {% for product in order.products.all %}
    {% if not product.id in products_ids %}
    <li>{{ product.name }}</li>
    {% with products_ids|add:product.id as products_ids %}
    {% endwith %}
    {% endif %}
    {% endfor %}
    {% endfor %}
</ul>

<h2>Заказы за год:</h2>
<ul>
    {% for order in orders_year %}
    {% for product in order.products.all %}
    {% if not product.id in products_ids %}
    <li>{{ product.name }}</li>
    {% with products_ids|add:product.id as products_ids %}
    {% endwith %}
    {% endif %}
    {% endfor %}
    {% endfor %}
</ul>
</body>

gb_project/hello_app/templates/hello_app/photo_form.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Загрузка фотографии продукта</title>
</head>
<body>
<h1>Загрузка фотографии продукта</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_photo">Выберите фото продукта:</label><br>
    <input type="file" name="photo" id="id_photo"><br><br>
    <input type="submit" value="Загрузить">
</form>
</body>
</html>